// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlh

import (
	"github.com/gosoline-project/sqlr"
	mock "github.com/stretchr/testify/mock"
)

// NewBuilderQueryAware creates a new instance of BuilderQueryAware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuilderQueryAware(t interface {
	mock.TestingT
	Cleanup(func())
}) *BuilderQueryAware {
	mock := &BuilderQueryAware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BuilderQueryAware is an autogenerated mock type for the BuilderQueryAware type
type BuilderQueryAware struct {
	mock.Mock
}

type BuilderQueryAware_Expecter struct {
	mock *mock.Mock
}

func (_m *BuilderQueryAware) EXPECT() *BuilderQueryAware_Expecter {
	return &BuilderQueryAware_Expecter{mock: &_m.Mock}
}

// BuilderQuery provides a mock function for the type BuilderQueryAware
func (_mock *BuilderQueryAware) BuilderQuery(qb *sqlr.QueryBuilderSelect) {
	_mock.Called(qb)
	return
}

// BuilderQueryAware_BuilderQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuilderQuery'
type BuilderQueryAware_BuilderQuery_Call struct {
	*mock.Call
}

// BuilderQuery is a helper method to define mock.On call
//   - qb *sqlr.QueryBuilderSelect
func (_e *BuilderQueryAware_Expecter) BuilderQuery(qb interface{}) *BuilderQueryAware_BuilderQuery_Call {
	return &BuilderQueryAware_BuilderQuery_Call{Call: _e.mock.On("BuilderQuery", qb)}
}

func (_c *BuilderQueryAware_BuilderQuery_Call) Run(run func(qb *sqlr.QueryBuilderSelect)) *BuilderQueryAware_BuilderQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sqlr.QueryBuilderSelect
		if args[0] != nil {
			arg0 = args[0].(*sqlr.QueryBuilderSelect)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BuilderQueryAware_BuilderQuery_Call) Return() *BuilderQueryAware_BuilderQuery_Call {
	_c.Call.Return()
	return _c
}

func (_c *BuilderQueryAware_BuilderQuery_Call) RunAndReturn(run func(qb *sqlr.QueryBuilderSelect)) *BuilderQueryAware_BuilderQuery_Call {
	_c.Run(run)
	return _c
}
