// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlh

import (
	"github.com/gosoline-project/sqlr"
	mock "github.com/stretchr/testify/mock"
)

// NewBuilderUpdateWriteAware creates a new instance of BuilderUpdateWriteAware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuilderUpdateWriteAware(t interface {
	mock.TestingT
	Cleanup(func())
}) *BuilderUpdateWriteAware {
	mock := &BuilderUpdateWriteAware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BuilderUpdateWriteAware is an autogenerated mock type for the BuilderUpdateWriteAware type
type BuilderUpdateWriteAware struct {
	mock.Mock
}

type BuilderUpdateWriteAware_Expecter struct {
	mock *mock.Mock
}

func (_m *BuilderUpdateWriteAware) EXPECT() *BuilderUpdateWriteAware_Expecter {
	return &BuilderUpdateWriteAware_Expecter{mock: &_m.Mock}
}

// BuilderUpdateWrite provides a mock function for the type BuilderUpdateWriteAware
func (_mock *BuilderUpdateWriteAware) BuilderUpdateWrite(qb *sqlr.QueryBuilderUpdate) {
	_mock.Called(qb)
	return
}

// BuilderUpdateWriteAware_BuilderUpdateWrite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuilderUpdateWrite'
type BuilderUpdateWriteAware_BuilderUpdateWrite_Call struct {
	*mock.Call
}

// BuilderUpdateWrite is a helper method to define mock.On call
//   - qb *sqlr.QueryBuilderUpdate
func (_e *BuilderUpdateWriteAware_Expecter) BuilderUpdateWrite(qb interface{}) *BuilderUpdateWriteAware_BuilderUpdateWrite_Call {
	return &BuilderUpdateWriteAware_BuilderUpdateWrite_Call{Call: _e.mock.On("BuilderUpdateWrite", qb)}
}

func (_c *BuilderUpdateWriteAware_BuilderUpdateWrite_Call) Run(run func(qb *sqlr.QueryBuilderUpdate)) *BuilderUpdateWriteAware_BuilderUpdateWrite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sqlr.QueryBuilderUpdate
		if args[0] != nil {
			arg0 = args[0].(*sqlr.QueryBuilderUpdate)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BuilderUpdateWriteAware_BuilderUpdateWrite_Call) Return() *BuilderUpdateWriteAware_BuilderUpdateWrite_Call {
	_c.Call.Return()
	return _c
}

func (_c *BuilderUpdateWriteAware_BuilderUpdateWrite_Call) RunAndReturn(run func(qb *sqlr.QueryBuilderUpdate)) *BuilderUpdateWriteAware_BuilderUpdateWrite_Call {
	_c.Run(run)
	return _c
}
