// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlh

import (
	"github.com/gosoline-project/sqlr"
	mock "github.com/stretchr/testify/mock"
)

// NewBuilderCreateAware creates a new instance of BuilderCreateAware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuilderCreateAware(t interface {
	mock.TestingT
	Cleanup(func())
}) *BuilderCreateAware {
	mock := &BuilderCreateAware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BuilderCreateAware is an autogenerated mock type for the BuilderCreateAware type
type BuilderCreateAware struct {
	mock.Mock
}

type BuilderCreateAware_Expecter struct {
	mock *mock.Mock
}

func (_m *BuilderCreateAware) EXPECT() *BuilderCreateAware_Expecter {
	return &BuilderCreateAware_Expecter{mock: &_m.Mock}
}

// BuilderCreate provides a mock function for the type BuilderCreateAware
func (_mock *BuilderCreateAware) BuilderCreate(qb *sqlr.QueryBuilderCreate) {
	_mock.Called(qb)
	return
}

// BuilderCreateAware_BuilderCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuilderCreate'
type BuilderCreateAware_BuilderCreate_Call struct {
	*mock.Call
}

// BuilderCreate is a helper method to define mock.On call
//   - qb *sqlr.QueryBuilderCreate
func (_e *BuilderCreateAware_Expecter) BuilderCreate(qb interface{}) *BuilderCreateAware_BuilderCreate_Call {
	return &BuilderCreateAware_BuilderCreate_Call{Call: _e.mock.On("BuilderCreate", qb)}
}

func (_c *BuilderCreateAware_BuilderCreate_Call) Run(run func(qb *sqlr.QueryBuilderCreate)) *BuilderCreateAware_BuilderCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sqlr.QueryBuilderCreate
		if args[0] != nil {
			arg0 = args[0].(*sqlr.QueryBuilderCreate)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BuilderCreateAware_BuilderCreate_Call) Return() *BuilderCreateAware_BuilderCreate_Call {
	_c.Call.Return()
	return _c
}

func (_c *BuilderCreateAware_BuilderCreate_Call) RunAndReturn(run func(qb *sqlr.QueryBuilderCreate)) *BuilderCreateAware_BuilderCreate_Call {
	_c.Run(run)
	return _c
}
