// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlh

import (
	"github.com/gosoline-project/sqlr"
	mock "github.com/stretchr/testify/mock"
)

// NewBuilderUpdateReadAware creates a new instance of BuilderUpdateReadAware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuilderUpdateReadAware(t interface {
	mock.TestingT
	Cleanup(func())
}) *BuilderUpdateReadAware {
	mock := &BuilderUpdateReadAware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BuilderUpdateReadAware is an autogenerated mock type for the BuilderUpdateReadAware type
type BuilderUpdateReadAware struct {
	mock.Mock
}

type BuilderUpdateReadAware_Expecter struct {
	mock *mock.Mock
}

func (_m *BuilderUpdateReadAware) EXPECT() *BuilderUpdateReadAware_Expecter {
	return &BuilderUpdateReadAware_Expecter{mock: &_m.Mock}
}

// BuilderUpdateRead provides a mock function for the type BuilderUpdateReadAware
func (_mock *BuilderUpdateReadAware) BuilderUpdateRead(qb *sqlr.QueryBuilderRead) {
	_mock.Called(qb)
	return
}

// BuilderUpdateReadAware_BuilderUpdateRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuilderUpdateRead'
type BuilderUpdateReadAware_BuilderUpdateRead_Call struct {
	*mock.Call
}

// BuilderUpdateRead is a helper method to define mock.On call
//   - qb *sqlr.QueryBuilderRead
func (_e *BuilderUpdateReadAware_Expecter) BuilderUpdateRead(qb interface{}) *BuilderUpdateReadAware_BuilderUpdateRead_Call {
	return &BuilderUpdateReadAware_BuilderUpdateRead_Call{Call: _e.mock.On("BuilderUpdateRead", qb)}
}

func (_c *BuilderUpdateReadAware_BuilderUpdateRead_Call) Run(run func(qb *sqlr.QueryBuilderRead)) *BuilderUpdateReadAware_BuilderUpdateRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sqlr.QueryBuilderRead
		if args[0] != nil {
			arg0 = args[0].(*sqlr.QueryBuilderRead)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BuilderUpdateReadAware_BuilderUpdateRead_Call) Return() *BuilderUpdateReadAware_BuilderUpdateRead_Call {
	_c.Call.Return()
	return _c
}

func (_c *BuilderUpdateReadAware_BuilderUpdateRead_Call) RunAndReturn(run func(qb *sqlr.QueryBuilderRead)) *BuilderUpdateReadAware_BuilderUpdateRead_Call {
	_c.Run(run)
	return _c
}
