// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlh

import (
	"github.com/gosoline-project/sqlr"
	mock "github.com/stretchr/testify/mock"
)

// NewBuilderReadAware creates a new instance of BuilderReadAware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuilderReadAware(t interface {
	mock.TestingT
	Cleanup(func())
}) *BuilderReadAware {
	mock := &BuilderReadAware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BuilderReadAware is an autogenerated mock type for the BuilderReadAware type
type BuilderReadAware struct {
	mock.Mock
}

type BuilderReadAware_Expecter struct {
	mock *mock.Mock
}

func (_m *BuilderReadAware) EXPECT() *BuilderReadAware_Expecter {
	return &BuilderReadAware_Expecter{mock: &_m.Mock}
}

// BuilderRead provides a mock function for the type BuilderReadAware
func (_mock *BuilderReadAware) BuilderRead(qb *sqlr.QueryBuilderRead) {
	_mock.Called(qb)
	return
}

// BuilderReadAware_BuilderRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuilderRead'
type BuilderReadAware_BuilderRead_Call struct {
	*mock.Call
}

// BuilderRead is a helper method to define mock.On call
//   - qb *sqlr.QueryBuilderRead
func (_e *BuilderReadAware_Expecter) BuilderRead(qb interface{}) *BuilderReadAware_BuilderRead_Call {
	return &BuilderReadAware_BuilderRead_Call{Call: _e.mock.On("BuilderRead", qb)}
}

func (_c *BuilderReadAware_BuilderRead_Call) Run(run func(qb *sqlr.QueryBuilderRead)) *BuilderReadAware_BuilderRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sqlr.QueryBuilderRead
		if args[0] != nil {
			arg0 = args[0].(*sqlr.QueryBuilderRead)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BuilderReadAware_BuilderRead_Call) Return() *BuilderReadAware_BuilderRead_Call {
	_c.Call.Return()
	return _c
}

func (_c *BuilderReadAware_BuilderRead_Call) RunAndReturn(run func(qb *sqlr.QueryBuilderRead)) *BuilderReadAware_BuilderRead_Call {
	_c.Run(run)
	return _c
}
