// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlh

import (
	"github.com/gosoline-project/sqlr"
	mock "github.com/stretchr/testify/mock"
)

// NewBuilderDeleteAware creates a new instance of BuilderDeleteAware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuilderDeleteAware(t interface {
	mock.TestingT
	Cleanup(func())
}) *BuilderDeleteAware {
	mock := &BuilderDeleteAware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BuilderDeleteAware is an autogenerated mock type for the BuilderDeleteAware type
type BuilderDeleteAware struct {
	mock.Mock
}

type BuilderDeleteAware_Expecter struct {
	mock *mock.Mock
}

func (_m *BuilderDeleteAware) EXPECT() *BuilderDeleteAware_Expecter {
	return &BuilderDeleteAware_Expecter{mock: &_m.Mock}
}

// BuilderDelete provides a mock function for the type BuilderDeleteAware
func (_mock *BuilderDeleteAware) BuilderDelete(qb *sqlr.QueryBuilderDelete) {
	_mock.Called(qb)
	return
}

// BuilderDeleteAware_BuilderDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuilderDelete'
type BuilderDeleteAware_BuilderDelete_Call struct {
	*mock.Call
}

// BuilderDelete is a helper method to define mock.On call
//   - qb *sqlr.QueryBuilderDelete
func (_e *BuilderDeleteAware_Expecter) BuilderDelete(qb interface{}) *BuilderDeleteAware_BuilderDelete_Call {
	return &BuilderDeleteAware_BuilderDelete_Call{Call: _e.mock.On("BuilderDelete", qb)}
}

func (_c *BuilderDeleteAware_BuilderDelete_Call) Run(run func(qb *sqlr.QueryBuilderDelete)) *BuilderDeleteAware_BuilderDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sqlr.QueryBuilderDelete
		if args[0] != nil {
			arg0 = args[0].(*sqlr.QueryBuilderDelete)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BuilderDeleteAware_BuilderDelete_Call) Return() *BuilderDeleteAware_BuilderDelete_Call {
	_c.Call.Return()
	return _c
}

func (_c *BuilderDeleteAware_BuilderDelete_Call) RunAndReturn(run func(qb *sqlr.QueryBuilderDelete)) *BuilderDeleteAware_BuilderDelete_Call {
	_c.Run(run)
	return _c
}
