// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlh

import (
	"context"

	"github.com/gosoline-project/sqlr"
	mock "github.com/stretchr/testify/mock"
)

// NewJsonResultsTransformer creates a new instance of JsonResultsTransformer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJsonResultsTransformer[K sqlr.KeyTypes, E sqlr.Entitier[K], IC any, IU any](t interface {
	mock.TestingT
	Cleanup(func())
}) *JsonResultsTransformer[K, E, IC, IU] {
	mock := &JsonResultsTransformer[K, E, IC, IU]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JsonResultsTransformer is an autogenerated mock type for the JsonResultsTransformer type
type JsonResultsTransformer[K sqlr.KeyTypes, E sqlr.Entitier[K], IC any, IU any] struct {
	mock.Mock
}

type JsonResultsTransformer_Expecter[K sqlr.KeyTypes, E sqlr.Entitier[K], IC any, IU any] struct {
	mock *mock.Mock
}

func (_m *JsonResultsTransformer[K, E, IC, IU]) EXPECT() *JsonResultsTransformer_Expecter[K, E, IC, IU] {
	return &JsonResultsTransformer_Expecter[K, E, IC, IU]{mock: &_m.Mock}
}

// TransformCreateInput provides a mock function for the type JsonResultsTransformer
func (_mock *JsonResultsTransformer[K, E, IC, IU]) TransformCreateInput(ctx context.Context, input *IC) (*E, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for TransformCreateInput")
	}

	var r0 *E
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *IC) (*E, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *IC) *E); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*E)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *IC) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JsonResultsTransformer_TransformCreateInput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransformCreateInput'
type JsonResultsTransformer_TransformCreateInput_Call[K sqlr.KeyTypes, E sqlr.Entitier[K], IC any, IU any] struct {
	*mock.Call
}

// TransformCreateInput is a helper method to define mock.On call
//   - ctx context.Context
//   - input *IC
func (_e *JsonResultsTransformer_Expecter[K, E, IC, IU]) TransformCreateInput(ctx interface{}, input interface{}) *JsonResultsTransformer_TransformCreateInput_Call[K, E, IC, IU] {
	return &JsonResultsTransformer_TransformCreateInput_Call[K, E, IC, IU]{Call: _e.mock.On("TransformCreateInput", ctx, input)}
}

func (_c *JsonResultsTransformer_TransformCreateInput_Call[K, E, IC, IU]) Run(run func(ctx context.Context, input *IC)) *JsonResultsTransformer_TransformCreateInput_Call[K, E, IC, IU] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *IC
		if args[1] != nil {
			arg1 = args[1].(*IC)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JsonResultsTransformer_TransformCreateInput_Call[K, E, IC, IU]) Return(v *E, err error) *JsonResultsTransformer_TransformCreateInput_Call[K, E, IC, IU] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *JsonResultsTransformer_TransformCreateInput_Call[K, E, IC, IU]) RunAndReturn(run func(ctx context.Context, input *IC) (*E, error)) *JsonResultsTransformer_TransformCreateInput_Call[K, E, IC, IU] {
	_c.Call.Return(run)
	return _c
}

// TransformOutput provides a mock function for the type JsonResultsTransformer
func (_mock *JsonResultsTransformer[K, E, IC, IU]) TransformOutput(ctx context.Context, entity *E) (any, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for TransformOutput")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *E) (any, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *E) any); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *E) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JsonResultsTransformer_TransformOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransformOutput'
type JsonResultsTransformer_TransformOutput_Call[K sqlr.KeyTypes, E sqlr.Entitier[K], IC any, IU any] struct {
	*mock.Call
}

// TransformOutput is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *E
func (_e *JsonResultsTransformer_Expecter[K, E, IC, IU]) TransformOutput(ctx interface{}, entity interface{}) *JsonResultsTransformer_TransformOutput_Call[K, E, IC, IU] {
	return &JsonResultsTransformer_TransformOutput_Call[K, E, IC, IU]{Call: _e.mock.On("TransformOutput", ctx, entity)}
}

func (_c *JsonResultsTransformer_TransformOutput_Call[K, E, IC, IU]) Run(run func(ctx context.Context, entity *E)) *JsonResultsTransformer_TransformOutput_Call[K, E, IC, IU] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *E
		if args[1] != nil {
			arg1 = args[1].(*E)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JsonResultsTransformer_TransformOutput_Call[K, E, IC, IU]) Return(v any, err error) *JsonResultsTransformer_TransformOutput_Call[K, E, IC, IU] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *JsonResultsTransformer_TransformOutput_Call[K, E, IC, IU]) RunAndReturn(run func(ctx context.Context, entity *E) (any, error)) *JsonResultsTransformer_TransformOutput_Call[K, E, IC, IU] {
	_c.Call.Return(run)
	return _c
}

// TransformUpdateInput provides a mock function for the type JsonResultsTransformer
func (_mock *JsonResultsTransformer[K, E, IC, IU]) TransformUpdateInput(ctx context.Context, entity *E, input *IU) (*E, error) {
	ret := _mock.Called(ctx, entity, input)

	if len(ret) == 0 {
		panic("no return value specified for TransformUpdateInput")
	}

	var r0 *E
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *E, *IU) (*E, error)); ok {
		return returnFunc(ctx, entity, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *E, *IU) *E); ok {
		r0 = returnFunc(ctx, entity, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*E)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *E, *IU) error); ok {
		r1 = returnFunc(ctx, entity, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JsonResultsTransformer_TransformUpdateInput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransformUpdateInput'
type JsonResultsTransformer_TransformUpdateInput_Call[K sqlr.KeyTypes, E sqlr.Entitier[K], IC any, IU any] struct {
	*mock.Call
}

// TransformUpdateInput is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *E
//   - input *IU
func (_e *JsonResultsTransformer_Expecter[K, E, IC, IU]) TransformUpdateInput(ctx interface{}, entity interface{}, input interface{}) *JsonResultsTransformer_TransformUpdateInput_Call[K, E, IC, IU] {
	return &JsonResultsTransformer_TransformUpdateInput_Call[K, E, IC, IU]{Call: _e.mock.On("TransformUpdateInput", ctx, entity, input)}
}

func (_c *JsonResultsTransformer_TransformUpdateInput_Call[K, E, IC, IU]) Run(run func(ctx context.Context, entity *E, input *IU)) *JsonResultsTransformer_TransformUpdateInput_Call[K, E, IC, IU] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *E
		if args[1] != nil {
			arg1 = args[1].(*E)
		}
		var arg2 *IU
		if args[2] != nil {
			arg2 = args[2].(*IU)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *JsonResultsTransformer_TransformUpdateInput_Call[K, E, IC, IU]) Return(v *E, err error) *JsonResultsTransformer_TransformUpdateInput_Call[K, E, IC, IU] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *JsonResultsTransformer_TransformUpdateInput_Call[K, E, IC, IU]) RunAndReturn(run func(ctx context.Context, entity *E, input *IU) (*E, error)) *JsonResultsTransformer_TransformUpdateInput_Call[K, E, IC, IU] {
	_c.Call.Return(run)
	return _c
}
