// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlh

import (
	"context"

	"github.com/gosoline-project/httpserver"
	"github.com/gosoline-project/sqlr"
	mock "github.com/stretchr/testify/mock"
)

// NewTransformer creates a new instance of Transformer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransformer[K sqlr.KeyTypes, E sqlr.Entitier[K], IC any, IU any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Transformer[K, E, IC, IU] {
	mock := &Transformer[K, E, IC, IU]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Transformer is an autogenerated mock type for the Transformer type
type Transformer[K sqlr.KeyTypes, E sqlr.Entitier[K], IC any, IU any] struct {
	mock.Mock
}

type Transformer_Expecter[K sqlr.KeyTypes, E sqlr.Entitier[K], IC any, IU any] struct {
	mock *mock.Mock
}

func (_m *Transformer[K, E, IC, IU]) EXPECT() *Transformer_Expecter[K, E, IC, IU] {
	return &Transformer_Expecter[K, E, IC, IU]{mock: &_m.Mock}
}

// RenderEntityResponse provides a mock function for the type Transformer
func (_mock *Transformer[K, E, IC, IU]) RenderEntityResponse(ctx context.Context, entity *E) (httpserver.Response, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for RenderEntityResponse")
	}

	var r0 httpserver.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *E) (httpserver.Response, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *E) httpserver.Response); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpserver.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *E) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Transformer_RenderEntityResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderEntityResponse'
type Transformer_RenderEntityResponse_Call[K sqlr.KeyTypes, E sqlr.Entitier[K], IC any, IU any] struct {
	*mock.Call
}

// RenderEntityResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *E
func (_e *Transformer_Expecter[K, E, IC, IU]) RenderEntityResponse(ctx interface{}, entity interface{}) *Transformer_RenderEntityResponse_Call[K, E, IC, IU] {
	return &Transformer_RenderEntityResponse_Call[K, E, IC, IU]{Call: _e.mock.On("RenderEntityResponse", ctx, entity)}
}

func (_c *Transformer_RenderEntityResponse_Call[K, E, IC, IU]) Run(run func(ctx context.Context, entity *E)) *Transformer_RenderEntityResponse_Call[K, E, IC, IU] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *E
		if args[1] != nil {
			arg1 = args[1].(*E)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Transformer_RenderEntityResponse_Call[K, E, IC, IU]) Return(response httpserver.Response, err error) *Transformer_RenderEntityResponse_Call[K, E, IC, IU] {
	_c.Call.Return(response, err)
	return _c
}

func (_c *Transformer_RenderEntityResponse_Call[K, E, IC, IU]) RunAndReturn(run func(ctx context.Context, entity *E) (httpserver.Response, error)) *Transformer_RenderEntityResponse_Call[K, E, IC, IU] {
	_c.Call.Return(run)
	return _c
}

// RenderQueryResponse provides a mock function for the type Transformer
func (_mock *Transformer[K, E, IC, IU]) RenderQueryResponse(ctx context.Context, entity []E) (httpserver.Response, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for RenderQueryResponse")
	}

	var r0 httpserver.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []E) (httpserver.Response, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []E) httpserver.Response); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpserver.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []E) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Transformer_RenderQueryResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderQueryResponse'
type Transformer_RenderQueryResponse_Call[K sqlr.KeyTypes, E sqlr.Entitier[K], IC any, IU any] struct {
	*mock.Call
}

// RenderQueryResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - entity []E
func (_e *Transformer_Expecter[K, E, IC, IU]) RenderQueryResponse(ctx interface{}, entity interface{}) *Transformer_RenderQueryResponse_Call[K, E, IC, IU] {
	return &Transformer_RenderQueryResponse_Call[K, E, IC, IU]{Call: _e.mock.On("RenderQueryResponse", ctx, entity)}
}

func (_c *Transformer_RenderQueryResponse_Call[K, E, IC, IU]) Run(run func(ctx context.Context, entity []E)) *Transformer_RenderQueryResponse_Call[K, E, IC, IU] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []E
		if args[1] != nil {
			arg1 = args[1].([]E)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Transformer_RenderQueryResponse_Call[K, E, IC, IU]) Return(response httpserver.Response, err error) *Transformer_RenderQueryResponse_Call[K, E, IC, IU] {
	_c.Call.Return(response, err)
	return _c
}

func (_c *Transformer_RenderQueryResponse_Call[K, E, IC, IU]) RunAndReturn(run func(ctx context.Context, entity []E) (httpserver.Response, error)) *Transformer_RenderQueryResponse_Call[K, E, IC, IU] {
	_c.Call.Return(run)
	return _c
}

// TransformCreateInput provides a mock function for the type Transformer
func (_mock *Transformer[K, E, IC, IU]) TransformCreateInput(ctx context.Context, input *IC) (*E, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for TransformCreateInput")
	}

	var r0 *E
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *IC) (*E, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *IC) *E); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*E)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *IC) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Transformer_TransformCreateInput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransformCreateInput'
type Transformer_TransformCreateInput_Call[K sqlr.KeyTypes, E sqlr.Entitier[K], IC any, IU any] struct {
	*mock.Call
}

// TransformCreateInput is a helper method to define mock.On call
//   - ctx context.Context
//   - input *IC
func (_e *Transformer_Expecter[K, E, IC, IU]) TransformCreateInput(ctx interface{}, input interface{}) *Transformer_TransformCreateInput_Call[K, E, IC, IU] {
	return &Transformer_TransformCreateInput_Call[K, E, IC, IU]{Call: _e.mock.On("TransformCreateInput", ctx, input)}
}

func (_c *Transformer_TransformCreateInput_Call[K, E, IC, IU]) Run(run func(ctx context.Context, input *IC)) *Transformer_TransformCreateInput_Call[K, E, IC, IU] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *IC
		if args[1] != nil {
			arg1 = args[1].(*IC)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Transformer_TransformCreateInput_Call[K, E, IC, IU]) Return(v *E, err error) *Transformer_TransformCreateInput_Call[K, E, IC, IU] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Transformer_TransformCreateInput_Call[K, E, IC, IU]) RunAndReturn(run func(ctx context.Context, input *IC) (*E, error)) *Transformer_TransformCreateInput_Call[K, E, IC, IU] {
	_c.Call.Return(run)
	return _c
}

// TransformUpdateInput provides a mock function for the type Transformer
func (_mock *Transformer[K, E, IC, IU]) TransformUpdateInput(ctx context.Context, entity *E, input *IU) (*E, error) {
	ret := _mock.Called(ctx, entity, input)

	if len(ret) == 0 {
		panic("no return value specified for TransformUpdateInput")
	}

	var r0 *E
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *E, *IU) (*E, error)); ok {
		return returnFunc(ctx, entity, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *E, *IU) *E); ok {
		r0 = returnFunc(ctx, entity, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*E)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *E, *IU) error); ok {
		r1 = returnFunc(ctx, entity, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Transformer_TransformUpdateInput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransformUpdateInput'
type Transformer_TransformUpdateInput_Call[K sqlr.KeyTypes, E sqlr.Entitier[K], IC any, IU any] struct {
	*mock.Call
}

// TransformUpdateInput is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *E
//   - input *IU
func (_e *Transformer_Expecter[K, E, IC, IU]) TransformUpdateInput(ctx interface{}, entity interface{}, input interface{}) *Transformer_TransformUpdateInput_Call[K, E, IC, IU] {
	return &Transformer_TransformUpdateInput_Call[K, E, IC, IU]{Call: _e.mock.On("TransformUpdateInput", ctx, entity, input)}
}

func (_c *Transformer_TransformUpdateInput_Call[K, E, IC, IU]) Run(run func(ctx context.Context, entity *E, input *IU)) *Transformer_TransformUpdateInput_Call[K, E, IC, IU] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *E
		if args[1] != nil {
			arg1 = args[1].(*E)
		}
		var arg2 *IU
		if args[2] != nil {
			arg2 = args[2].(*IU)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Transformer_TransformUpdateInput_Call[K, E, IC, IU]) Return(v *E, err error) *Transformer_TransformUpdateInput_Call[K, E, IC, IU] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Transformer_TransformUpdateInput_Call[K, E, IC, IU]) RunAndReturn(run func(ctx context.Context, entity *E, input *IU) (*E, error)) *Transformer_TransformUpdateInput_Call[K, E, IC, IU] {
	_c.Call.Return(run)
	return _c
}
